name: pizza
description: Application flutter
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.0
  dio: ^5.4.3+1
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.8
  connectivity_plus: ^6.0.3
  camera: ^0.11.0+1
  flutter_map: ^7.0.1
  flutter_vector_icons: ^2.0.0
  supabase_flutter: ^2.5.6
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color_web: "#FF2D00"